from tkinter import *

root = Tk()
root.title("Untitled - Notepad")
root.geometry("1120x550")

textarea = Text(root, font="ariel").pack(expand=True, fill=BOTH)

menu = Menu(root)
item1 = Menu(menu, tearoff=0)
item1.add_command(label="New", command="")
item1.add_command(label="New Window", command="")
item1.add_command(label="Open...", command="")
item1.add_command(label="Save", command="")
item1.add_command(label="Save As...", command="")
item1.add_separator()
item1.add_command(label="Page Setup...", command="")
item1.add_command(label="Print....", command="")
item1.add_separator()
item1.add_command(label="Exit", command=quit)
menu.add_cascade(label="File", menu=item1)

item2 = Menu(menu, tearoff=0)
item2.add_command(label="Undo", command="")
item2.add_command(label="Redo", command="")
item2.add_separator()
item2.add_command(label="Cut", command="")
item2.add_command(label="Copy", command="")
item2.add_command(label="Paste", command="")
item2.add_command(label="Delete", command="")
item2.add_separator()
item2.add_command(label="Find", command="")
item2.add_command(label="Replace", command="")
item2.add_separator()
item2.add_command(label="Select All", command="")
item2.add_command(label="Time/Date", command="")
menu.add_cascade(label="Edit", menu=item2)

item3 = Menu(menu, tearoff=0)
item3.add_checkbutton(label="Word Wrap", command="")
item3.add_command(label="Font...", command="")
menu.add_cascade(label="Format", menu=item3)

item4 = Menu(menu, tearoff=0)
item4menu = Menu(item4, tearoff=0)
item4.add_cascade(label="Zoom", menu=item4menu)
item4menu.add_command(label="Zoom In", command="")
item4menu.add_command(label="Zoom Out", command="")
item4menu.add_command(label="Restore Default Zoom", command="")
item4.add_checkbutton(label="Status Bar", command="")
menu.add_cascade(label="View", menu=item4)

item5 = Menu(menu, tearoff=0)
item5.add_command(label="View Help", command="")
item5.add_command(label="Send Feedback", command="")
item5.add_separator()
item5.add_command(label="About Aayan Yasin", command="")
menu.add_cascade(label="Help", menu=item5)

root.config(menu=menu)

root.mainloop()
